// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAXDBVQ5QR1Byj8oFmQ89ETxV-vPxvtdU',
    appId: '1:995160794905:web:85b25dec2c5d07ed2e4788',
    messagingSenderId: '995160794905',
    projectId: 'biznet-workforce-activity-app',
    authDomain: 'biznet-workforce-activity-app.firebaseapp.com',
    storageBucket: 'biznet-workforce-activity-app.firebasestorage.app',
    measurementId: 'G-PL5LHMGW8C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6cXoTM6KIm8LJpelIRxIyaukBpa9pHz0',
    appId: '1:995160794905:android:cc364a763755feae2e4788',
    messagingSenderId: '995160794905',
    projectId: 'biznet-workforce-activity-app',
    storageBucket: 'biznet-workforce-activity-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9VDW9X-A8-Y-6S-0vSbWNRWipRvJ9ZAE',
    appId: '1:995160794905:ios:23f737fce9b526962e4788',
    messagingSenderId: '995160794905',
    projectId: 'biznet-workforce-activity-app',
    storageBucket: 'biznet-workforce-activity-app.firebasestorage.app',
    iosBundleId: 'com.example.biznetWorkforceActivity',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9VDW9X-A8-Y-6S-0vSbWNRWipRvJ9ZAE',
    appId: '1:995160794905:ios:23f737fce9b526962e4788',
    messagingSenderId: '995160794905',
    projectId: 'biznet-workforce-activity-app',
    storageBucket: 'biznet-workforce-activity-app.firebasestorage.app',
    iosBundleId: 'com.example.biznetWorkforceActivity',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCAXDBVQ5QR1Byj8oFmQ89ETxV-vPxvtdU',
    appId: '1:995160794905:web:04fba42b3358ed942e4788',
    messagingSenderId: '995160794905',
    projectId: 'biznet-workforce-activity-app',
    authDomain: 'biznet-workforce-activity-app.firebaseapp.com',
    storageBucket: 'biznet-workforce-activity-app.firebasestorage.app',
    measurementId: 'G-1K9NZ2DM03',
  );
}
